config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :user

  
  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      devise_scope :user do
        match '/logins' => 'logins#create', :via => :post
        match '/logins' => 'logins#destroy', :via => :delete
        match '/registrations' => 'registrations#create', :via => :post
      end

      resources :users do
      	collection do
					get 'me'
				end
			end

      resources :waves do
      	member do 
      		get 'sessions'
      	end
      end
      
      resources :sessions do
        member do
          post 'upload'
        end
      end
      resources :buoys
      resources :observations
      resources :alerts
    end
  end

  # Admin views
  devise_for :admins
  resources :buoys do
    resources :observations
  end
  resources :wave_sessions
  resources :users
  resources :alerts
end

app/models/buoy.rb
class Buoy < ActiveRecord::Base
	extend Retryable
	acts_as_mappable :default_units => :miles, :lat_column_name => :latitude, :lng_column_name => :longitude

	has_many :observations
	belongs_to :current_observation, class_name: "Observation"
	belongs_to :tidal_buoy

	validates :station_id, uniqueness: true



	def self.import! buoy_id=nil # gets all buoys. Needs curration. BE CAREFUL
		buoy_list = BuoyData::NoaaBuoyList.new
		buoy_list.get({id: buoy_id})[:stations].each do |buoy|
			begin
				b = Buoy.create(
					title: buoy[:title],
					description: buoy[:description],
					station_id: buoy[:station_id],
					latitude: buoy[:lat],
					longitude: buoy[:lng]
					)
			rescue
				next
			end
		end
	end

	def self.import_observations! 
		#import current obversa for each buoy
		# heroku run simple cron jobs for each buoy
		# this runs each hour and grabs all info for each buoy
		# heroku scheduler 
		# rake file for custome jobs
		buoys = Buoy.all
		buoys.each do |buoy|
			begin
				puts buoy.title
				retryable(:tries => 3) do
					Observation.import! buoy
				end
				puts buoy.current_observation.inspect
			rescue
		  	next
		  end
		end
	end

	def self.import_observation_histories!
		buoys = Buoy.all
		buoys.each do |buoy|
			puts buoy.title
			Observation.import_history! buoy
		end
	end

end

app/controllers/api/v1/buoys_controller.rb
class Api::V1::BuoysController < APIController
	skip_before_filter :authenticate_user_from_token!, :except => [:create]
	skip_before_filter :authenticate_user!, :except => [:create]

	def index
		@buoys = Buoy.all.includes(:current_observation)
		expires_in 1.hour, :public => true
		respond_with @buoys
	end

	def show
		@buoy = Buoy.find(params[:id])
		respond_with @buoy
	end

	def to_json(thing)
      thing.to_json({include: {
        current_observation: {},
      }})
    end

  # def to_multi_json(thing) 
  # 	MultiJson.dump(buoys: thing.
  # end 


end

app/controllers/buoys_controller.rb
class BuoysController < AdminController
  before_action :set_buoy, only: [:show, :edit, :update, :destroy]

  # GET /buoys
  # GET /buoys.json
  def index
    @buoys = Buoy.all
  end

  # GET /buoys/1
  # GET /buoys/1.json
  def show
  end

  # GET /buoys/new
  def new
    @buoy = Buoy.new
  end

  # GET /buoys/1/edit
  def edit
  end

  # POST /buoys
  # POST /buoys.json
  def create
    @buoy = Buoy.new(buoy_params)

    respond_to do |format|
      if @buoy.save
        format.html { redirect_to @buoy, notice: 'Buoy was successfully created.' }
        format.json { render :show, status: :created, location: @buoy }
      else
        format.html { render :new }
        format.json { render json: @buoy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buoys/1
  # PATCH/PUT /buoys/1.json
  def update
    respond_to do |format|
      if @buoy.update(buoy_params)
        format.html { redirect_to @buoy, notice: 'Buoy was successfully updated.' }
        format.json { render :show, status: :ok, location: @buoy }
      else
        format.html { render :edit }
        format.json { render json: @buoy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buoys/1
  # DELETE /buoys/1.json
  def destroy
    @buoy.destroy
    respond_to do |format|
      format.html { redirect_to buoys_url, notice: 'Buoy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buoy
      @buoy = Buoy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def buoy_params
      params[:buoy].permit(:description)
    end
end

app/views/buoys/_form.html.erb
<%= simple_form_for(@buoy) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  	<%=  f.text_field :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/buoys/edit.html.erb
<h1>Editing buoy</h1>

<%= render 'form' %>

<%= link_to 'Show', @buoy %> |
<%= link_to 'Back', buoys_path %>

app/views/buoys/index.html.erb
<%= link_to 'users', users_path %> | 
<%= link_to 'buoys', buoys_path %> | 
<%= link_to 'sessions', wave_sessions_path %> 
<br />

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buoys.each do |buoy| %>
      <tr>
        <td><%= buoy.station_id %></td>
        <td><%= buoy.title %></td>
        <td><%= link_to 'Show', buoy %></td>
        <td><%= link_to 'Edit', edit_buoy_path(buoy) %></td>
        <td><%= link_to 'Destroy', buoy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Buoy', new_buoy_path %>

app/views/buoys/new.html.erb
<h1>New buoy</h1>

<%= render 'form' %>

<%= link_to 'Back', buoys_path %>

app/views/buoys/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_buoy_path(@buoy) %> |
<%= link_to 'Back', buoys_path %>

<h3> Current Observation </h3>
<table>
  <thead>
    <tr>
      <th>timestamp</th>
      <th>wave_height</th>
      <th>swell_height</th>
      <th>swell_period</th>
      <th>wind_wave_height</th>
      <th>wind_wave_period</th>
      <th>swell_direction</th>
      <th>steepness</th>
      <th>average_wave_period</th>
      <th>mean_wave_direction</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @buoy.current_observation.timestamp %></td>
        <td><%= @buoy.current_observation.wave_height %></td>
        <td><%= @buoy.current_observation.swell_height %></td>
        <td><%= @buoy.current_observation.swell_period %></td>
        <td><%= @buoy.current_observation.wind_wave_height %></td>
        <td><%= @buoy.current_observation.wind_wave_period %></td>
        <td><%= @buoy.current_observation.swell_direction %></td>
        <td><%= @buoy.current_observation.steepness %></td>
        <td><%= @buoy.current_observation.average_wave_period %></td>
        <td><%= @buoy.current_observation.mean_wave_direction %></td>
      </tr>
  </tbody>
</table>

<%= link_to 'all observations', buoy_observations_path(@buoy) %>