config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :user

  
  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      devise_scope :user do
        match '/logins' => 'logins#create', :via => :post
        match '/logins' => 'logins#destroy', :via => :delete
        match '/registrations' => 'registrations#create', :via => :post
      end

      resources :users do
      	collection do
					get 'me'
				end
			end

      resources :waves do
      	member do 
      		get 'sessions'
      	end
      end
      
      resources :sessions do
        member do
          post 'upload'
        end
      end
      resources :buoys
      resources :observations
      resources :alerts
    end
  end

  # Admin views
  devise_for :admins
  resources :buoys do
    resources :observations
  end
  resources :wave_sessions
  resources :users
  resources :alerts
end

app/controllers/wave_sessions_controller.rb
class WaveSessionsController < AdminController
  
  before_action :set_session, only: [:show, :edit, :update, :destroy]


  # GET /sessions
  # GET /sessions.json
  def index
    @sessions = Session.where(finalized: true).page(params[:page_id]).per(100)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sessions }
    end
  end

  # GET /sessions/1
  # GET /sessions/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @session }
    end
  end

  # GET /sessions/new
  def new
    @session = current_user.sessions.new
  end

  # GET /sessions/1/edit
  def edit
  end

  # POST /sessions
  # POST /sessions.json
  def create
    @session = SessionService.new(current_user).create_from_web! session_params

    respond_to do |format|
        format.html { redirect_to @session, notice: 'Session was successfully created.' }
        format.json { render json: @session, status: :created }
    end
  end

  # PATCH/PUT /sessions/1
  # PATCH/PUT /sessions/1.json
  def update
    respond_to do |format|
      if @session.update(session_params)
        format.html { redirect_to @session, notice: 'Session was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sessions/1
  # DELETE /sessions/1.json
  def destroy
    @session.destroy
    respond_to do |format|
      format.html { redirect_to sessions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_session
      @session = current_user.sessions.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def session_params
      params[:session].permit(:session_photo)
    end
end

app/views/wave_sessions/_form.html.erb
<%= simple_form_for(@session) do |f| %>
 
    <%= f.input :session_photo %>
    <%= f.submit %>
  
<% end %>

app/views/wave_sessions/edit.html.erb
<h1>Editing session</h1>

<%= render 'form' %>

<%= link_to 'Show', @session %> |
<%= link_to 'Back', sessions_path %>

app/views/wave_sessions/index.html.erb
<%= link_to 'users', users_path %> | 
<%= link_to 'buoys', buoys_path %> | 
<%= link_to 'sessions', wave_sessions_path %> 
<br />
<% @sessions.each do |session| %>
  <%= image_tag session.session_photo.feed.url %> <br />
  User: <%= session.wave.user.name %> <br />
  Rating: <%= session.rating %> <br />
  Comments: <%= session.notes %> <br />
<hr />     
<% end %>
  
<%= paginate @sessions %>

app/views/wave_sessions/new.html.erb
<h1>New session</h1>

<%= render 'form' %>

<%= link_to 'Back', sessions_path %>

app/views/wave_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_session_path(@session) %> |
<%= link_to 'Back', sessions_path %>

url: <%= @session.session_photo.url %>

<%= image_tag @session.session_photo.url %>

<% if @session.wave %>

<%= @session.wave.buoy.title %>
<% if @session.observation %>
<table>
  <thead>
    <tr>
      <th>timestamp</th>
      <th>wave_height</th>
      <th>swell_height</th>
      <th>swell_period</th>
      <th>wind_wave_height</th>
      <th>wind_wave_period</th>
      <th>swell_direction</th>
      <th>steepness</th>
      <th>average_wave_period</th>
      <th>mean_wave_direction</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @session.observation.timestamp %></td>
        <td><%= @session.observation.wave_height %></td>
        <td><%= @session.observation.swell_height %></td>
        <td><%= @session.observation.swell_period %></td>
        <td><%= @session.observation.wind_wave_height %></td>
        <td><%= @session.observation.wind_wave_period %></td>
        <td><%= @session.observation.swell_direction %></td>
        <td><%= @session.observation.steepness %></td>
        <td><%= @session.observation.average_wave_period %></td>
        <td><%= @session.observation.mean_wave_direction %></td>
      </tr>
    
  </tbody>
</table>
<% end %>
<% end %>